Eda in r studio filtering grouping plotting data
Phaneron97/R-workshop pull request #1
Opened 2024-04-28 17:56 UTC by Sara-Eftekhar-Azam

2024-05-02 19:03 UTC, Phaneron97 requested changes
It's unclear what has been done in this PR.

2024-05-02 19:09 UTC, Sara-Eftekhar-Azam commented
> It's unclear what has been done in this PR.

I have added some code that will import packages that are needed for the rest of the code such as ggplot2.
Next, I import mpg dataset from ggplot2 package. 
I have created a number of plots to illustrate different aspects of this dataset, including filtering data and grouping data.

2024-05-13 11:51 UTC, Bastiaan27 approved these changes
I really like this! The only thing to add is to create small and concise exsercises they can try on their own but try to keep it short so we don't run short on time 😄

2024-05-13 19:22 UTC, Sara-Eftekhar-Azam commented
I update the EDA part. I added 3 assignments in the file for participants to complete. They are very similar to what I have explained in the file.

2024-05-13 19:23 UTC, Sara-Eftekhar-Azam commented
> I really like this! The only thing to add is to create small and concise exsercises they can try on their own but try to keep it short so we don't run short on time 😄

Thanks for the comment. I added some short exercises (I called them assignments) in the code. Please have a look at them too.

2024-05-13 19:44 UTC, Phaneron97 requested changes
The tasks are well put together imo, great start although we should stick to just 1 dataset to make things easier for us and the participants. Could you use the dataset in `data/` during the tasks instead?

2024-05-13 19:44 UTC, Phaneron97 commented on code/EDA.Rmd
> -Task: plot city vs highway mileage. Show engine size and vehicle class as size and color.
I thought we spoke about using the same dataset? This probably makes it more difficult for us and the participants to check the correctness of all tasks and code. We should probably stick to just 1 dataset (the one in folder `data/` and do all analysis tasks on that.

2024-05-23 08:40 UTC, Bastiaan27 approved these changes
Nice work!!

2024-05-23 08:40 UTC, Phaneron97 approved these changes
all good, please merge 👍

2024-05-23 08:43 UTC, merged